# Generated by Django 5.2.17 on 2026-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(help_text='例如 "01", "02", "dietcontrol"', max_length=20, unique=True, verbose_name='專案編號')),
                ('icon', models.CharField(default='🚀', help_text='例如 "🔥", "📓", "📊", "🥗"', max_length=30, verbose_name='圖示/Emoji')),
                ('name_zh', models.CharField(max_length=100, verbose_name='應用名稱 (繁中)')),
                ('name_en', models.CharField(max_length=100, verbose_name='應用名稱 (英文)')),
                ('description_zh', models.TextField(verbose_name='功能簡介 (繁中)')),
                ('description_en', models.TextField(verbose_name='功能簡介 (英文)')),
                ('category', models.CharField(choices=[('habit', '習慣養成與挑戰 (Habits & Challenges)'), ('learning', '學習與知識管理 (Learning & Knowledge)'), ('lifestyle', '生活與健康記錄 (Lifestyle & Health)'), ('creative', '創意與 AI 工具 (Creative & AI Tools)'), ('social', '社群與互動探索 (Community & Social)'), ('other', '其他專案 (Other Apps)')], default='habit', max_length=30, verbose_name='應用分類')),
                ('route_path', models.CharField(help_text='例如 "/challenges/", "/journal/"', max_length=100, verbose_name='訪問路徑 (URL Prefix)')),
                ('target_port', models.PositiveIntegerField(default=8001, help_text='例如 8001, 8002', verbose_name='內部連接埠 (Host Port)')),
                ('status', models.CharField(choices=[('active', '正式上線 (Active)'), ('beta', '公測體驗 (Beta)'), ('upcoming', '即將推出 (Coming Soon)'), ('maintenance', '維護中 (Maintenance)')], default='active', max_length=20, verbose_name='營運狀態')),
                ('is_new', models.BooleanField(default=False, verbose_name='標記為本週新品 (✨ NEW)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在大廳啟用顯示')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='顯示排序 (由小到大)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '子應用模組',
                'verbose_name_plural': '子應用模組清單 (App Registry)',
                'ordering': ['display_order', 'app_id'],
            },
        ),
    ]
