services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alw-portal
    ports:
      - "8081:8000"
    env_file:
      - .env
    volumes:
      - ../dockerVolumn/00-UnifiedPortal:/app/data
    restart: unless-stopped


